# 1. Personal information card
# name = input()
# age = int(input())
# blood_group=input()
# serial_number=input()
# dept_no=int(input())
# print("Name ",name)
# print("Age ",age)
# print("Blood Group",blood_group)
# print("Serial Number",serial_number)
# print("Department",dept_no)

# 2 Calculator
# a = int(input("Enter the number "))
# b = int(input("Enter the number "))
# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
# print(a%b)
# print(a//b)

# # Area Calculator
# length = int(input("Enter the no"))
# breath = int(input("Enter the no"))
# radius = int(input("Enter the no"))
# print("Area of triangle",length*breath)
# print("Area of circle", 3.142*radius*radius)

# # 4 Temperature Converter
# Celsius = int(input("Enter the no "))
# print("The Fahrenheit is ", (Celsius*9/5)+32)

# # 5 Currency converter
# dollar = int(input("Enter the dollar "))
# print("The rupee value will be ",dollar*94.34)

# # 6 Age Calculator
# birth_year = int(input("Enter DOB "))
# year = 2026
# print("year will be ", year - birth_year)

# 7 Student marks calculator 
# physics = int(input("Enter the marks "))
# chemistry = int(input("Enter the marks "))
# maths = int(input("Enter the marks "))
# biology = int(input("Enter the marks "))
# total_marks = 400
# Overall_marks =  physics+chemistry+maths+biology
# print("percentage = ", (Overall_marks/total_marks)*100)

# MINI PROJECT
name = input("Enter Name ")
age = int(input("Enter Age "))
college = input("Enter College ")
branch = input("Enter Branch ")
print("Name :",name)
print("Age :",age)
print("College :",college)
print("branch :",branch)